---
kind: Namespace
apiVersion: v1
metadata:
  name: kevin
  labels:
    name: kevin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: kevin
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: kevin-web
  template:
    metadata:
      labels:
        app: kevin-web
    spec:
      containers:
        - name: web
          image: zaihuidev/kevin:code
          imagePullPolicy: Always
          command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
          env:
            - name: TZ
              value: "Asia/Shanghai"
            - name: LARK_APP_ID
              value: ""
            - name: LARK_APP_SECRET
              value: ""
            - name: LARK_VERIFY_TOKEN
              value: ""
            - name: LARK_ENCRYPT_KEY
              value: ""
            - name: REDIS_URL
              value: ""
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 100Mi
          ports:
            - containerPort: 8000
              name: web
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: kevin
spec:
  ports:
    - name: web
      port: 80
      targetPort: 8000
  selector:
    app: kevin-web
