# Generated by Django 3.1.2 on 2021-02-01 19:53

import datetime
import uuid

import hutils.django.databases
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="全宇宙唯一身份", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="上次修改时间")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        editable=False,
                        help_text="失效时间（1970年为未失效）",
                    ),
                ),
                ("name", models.CharField(blank=True, help_text="姓名", max_length=50, null=True, verbose_name="姓名")),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="手机号", max_length=11, null=True, unique=True, verbose_name="手机号"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, help_text="邮箱", max_length=50, null=True, unique=True, verbose_name="邮箱"
                    ),
                ),
                (
                    "default_jira_project",
                    models.CharField(default="ST", help_text="默认 Jira 项目", max_length=50, verbose_name="默认 Jira 项目"),
                ),
                (
                    "sync_calendar",
                    models.BooleanField(
                        default=False, help_text="开启 Jira 与企业微信的日程同步", verbose_name="开启 Jira 与企业微信的日程同步"
                    ),
                ),
                (
                    "default_gitlab_project",
                    models.CharField(help_text="默认 GitLab 项目", max_length=50, null=True, verbose_name="默认 GitLab 项目"),
                ),
                (
                    "unionid",
                    models.CharField(editable=False, max_length=30, null=True, unique=True, verbose_name="用户的 UnionID"),
                ),
                (
                    "alarm_openid",
                    models.CharField(
                        editable=False,
                        help_text="报警公众号的 OpenID",
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="报警公众号的 OpenID",
                    ),
                ),
                (
                    "is_subscribe",
                    models.BooleanField(default=False, editable=False, help_text="是否关注公众号", verbose_name="是否关注公众号"),
                ),
                (
                    "user_info",
                    models.TextField(default="{}", editable=False, help_text="微信用户信息", verbose_name="微信用户信息"),
                ),
                (
                    "wxwork_user_id",
                    models.CharField(
                        default="", editable=False, help_text="企业微信 UserId", max_length=30, verbose_name="企业微信 UserId"
                    ),
                ),
                (
                    "lark_open_id",
                    models.CharField(
                        editable=False, help_text="飞书 ID", max_length=50, null=True, unique=True, verbose_name="飞书 ID"
                    ),
                ),
                ("enable_vesta", models.BooleanField(default=False, help_text="开启美餐点餐", verbose_name="开启美餐点餐")),
                ("password_jira", models.CharField(default="", help_text="jira密码", max_length=256, null=True)),
            ],
            options={
                "verbose_name": "账号信息",
                "verbose_name_plural": "账号信息",
                "db_table": "ace_account",
            },
            bases=(models.Model, hutils.django.databases.ModelMixin),
        ),
    ]
