# Generated by Django 3.1.2 on 2021-02-03 14:32

import datetime
import uuid

import hutils.django.databases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0002_account_lark_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="LarkCallback",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="全宇宙唯一身份", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="上次修改时间")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        editable=False,
                        help_text="失效时间（1970年为未失效）",
                    ),
                ),
                (
                    "instance_code",
                    models.CharField(
                        editable=False, help_text="开课审批ID", max_length=50, null=True, unique=True, verbose_name="开课审批ID"
                    ),
                ),
                (
                    "callback_type",
                    models.CharField(
                        editable=False, help_text="飞书回调类型", max_length=50, null=True, verbose_name="飞书回调类型"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        editable=False, help_text="审批任务状态", max_length=50, null=True, verbose_name="审批任务状态"
                    ),
                ),
            ],
            options={
                "db_table": "ace_lark_callback",
            },
            bases=(models.Model, hutils.django.databases.ModelMixin),
        ),
        migrations.AddField(
            model_name="account",
            name="gua_id",
            field=models.CharField(
                editable=False, help_text="呱ID", max_length=50, null=True, unique=True, verbose_name="呱ID"
            ),
        ),
    ]
