# Generated by Django 3.1.2 on 2021-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0003_auto_20210203_1432"),
    ]

    operations = [
        migrations.AddField(
            model_name="larkcallback",
            name="approval_code",
            field=models.CharField(editable=False, help_text="任务code", max_length=50, null=True, verbose_name="任务code"),
        ),
        migrations.AlterField(
            model_name="larkcallback",
            name="instance_code",
            field=models.CharField(
                editable=False, help_text="实例code", max_length=50, null=True, unique=True, verbose_name="实例code"
            ),
        ),
    ]
