# Generated by Django 3.1.2 on 2021-02-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0004_auto_20210203_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="larkcallback",
            name="approval_name",
            field=models.CharField(editable=False, help_text="任务名称", max_length=50, null=True, verbose_name="任务名称"),
        ),
        migrations.AddField(
            model_name="larkcallback",
            name="form",
            field=models.CharField(help_text="审批表单详情", max_length=10000, null=True, verbose_name="审批表单详情"),
        ),
        migrations.AddField(
            model_name="larkcallback",
            name="user_id",
            field=models.CharField(help_text="提交人", max_length=50, null=True, verbose_name="提交人"),
        ),
        migrations.AlterField(
            model_name="larkcallback",
            name="instance_code",
            field=models.CharField(editable=False, help_text="实例code", max_length=50, null=True, verbose_name="实例code"),
        ),
    ]
