# Generated by Django 3.1.2 on 2021-02-05 04:07

import datetime
import uuid

import hutils.django.databases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0006_auto_20210205_0349"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="全宇宙唯一身份", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="上次修改时间")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        editable=False,
                        help_text="失效时间（1970年为未失效）",
                    ),
                ),
                ("name", models.CharField(blank=True, help_text="部门名称", max_length=50, null=True, verbose_name="部门名称")),
                (
                    "department_id",
                    models.CharField(
                        blank=True, help_text="部门ID", max_length=50, null=True, unique=True, verbose_name="部门ID"
                    ),
                ),
                (
                    "open_department_id",
                    models.CharField(
                        blank=True,
                        help_text="部门OPEN ID",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="部门OPEN ID",
                    ),
                ),
                (
                    "parent_department_id",
                    models.CharField(blank=True, help_text="父部门ID", max_length=50, null=True, verbose_name="父部门ID"),
                ),
                (
                    "parent_open_department_id",
                    models.CharField(
                        blank=True, help_text="父部门OPEN ID", max_length=50, null=True, verbose_name="父部门OPEN ID"
                    ),
                ),
                (
                    "leader_id",
                    models.CharField(
                        blank=True, help_text="leader ID", max_length=50, null=True, verbose_name="leader ID"
                    ),
                ),
                (
                    "count",
                    models.CharField(blank=True, help_text="部门人数", max_length=50, null=True, verbose_name="部门人数"),
                ),
            ],
            options={
                "db_table": "ace_department",
            },
            bases=(models.Model, hutils.django.databases.ModelMixin),
        ),
        migrations.CreateModel(
            name="DepartmentAccount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="全宇宙唯一身份", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="上次修改时间")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        editable=False,
                        help_text="失效时间（1970年为未失效）",
                    ),
                ),
                (
                    "open_department_id",
                    models.CharField(blank=True, help_text="部门 ID", max_length=50, verbose_name="部门 ID"),
                ),
                ("account_id", models.CharField(blank=True, help_text="用户ID", max_length=50, verbose_name="用户ID")),
            ],
            options={
                "db_table": "ace_department_account",
            },
            bases=(models.Model, hutils.django.databases.ModelMixin),
        ),
    ]
