# Generated by Django 3.1.2 on 2021-03-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0011_larkcallback_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="email",
            field=models.CharField(blank=True, help_text="邮箱", max_length=50, null=True, verbose_name="邮箱"),
        ),
    ]
