# Generated by Django 3.1.2 on 2021-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0012_auto_20210329_1320"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="english_name",
            field=models.CharField(blank=True, help_text="英文", max_length=50, null=True, verbose_name="英文"),
        ),
    ]
