# Generated by Django 3.1.2 on 2021-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0013_account_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="role",
            new_name="user_role",
        ),
    ]
