# Generated by Django 3.1.2 on 2021-04-09 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0014_larkcallback_ggr_result"),
        ("endpoints", "0014_auto_20210331_1526"),
    ]

    operations = []
