# Generated by Django 3.1.2 on 2021-04-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0017_auto_20210419_2300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="chat_id",
            field=models.CharField(blank=True, max_length=50, verbose_name="群聊id"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="is_active",
            field=models.BooleanField(blank=True, max_length=50, verbose_name="激活"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="project",
            field=models.CharField(blank=True, max_length=50, verbose_name="gitlab项目"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="source_branch",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="来源分支"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="target_branch",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="目标分支"),
        ),
    ]
