# Generated by Django 3.1.2 on 2021-05-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0020_larkcallback_niuwa_be_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="leader_email",
            field=models.CharField(
                blank=True, help_text="leader 邮箱", max_length=50, null=True, verbose_name="leader 邮箱"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent_open_department_ids",
            field=models.CharField(
                blank=True, help_text="父部门OPEN IDS", max_length=10000, null=True, verbose_name="父部门OPEN IDS"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="lark_open_id",
            field=models.CharField(editable=False, help_text="飞书 ID", max_length=50, null=True, verbose_name="飞书 ID"),
        ),
        migrations.AlterField(
            model_name="account",
            name="lark_user_id",
            field=models.CharField(
                editable=False, help_text="飞书 USER_ID", max_length=50, null=True, verbose_name="飞书 USER_ID"
            ),
        ),
    ]
