# Generated by Django 3.1.2 on 2021-05-31 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0020_larkcallback_niuwa_be_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="gitlabprojectchat",
            name="is_jira_active",
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name="gitlab与jira联动激活"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="群聊id"),
        ),
        migrations.AlterField(
            model_name="gitlabprojectchat",
            name="is_active",
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name="激活"),
        ),
    ]
