# Generated by Django 3.1.2 on 2021-06-03 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0021_auto_20210528_1402"),
        ("endpoints", "0021_auto_20210531_1450"),
    ]

    operations = []
