# Generated by Django 3.1.2 on 2021-06-21 10:46

import datetime
import uuid

import hutils.django.databases
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0024_storysubtaskrelation"),
    ]

    operations = [
        migrations.CreateModel(
            name="JiraProjectChat",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="全宇宙唯一身份", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="上次修改时间")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        db_index=True,
                        default=datetime.datetime(1970, 1, 1, 0, 0),
                        editable=False,
                        help_text="失效时间（1970年为未失效）",
                    ),
                ),
                ("project", models.CharField(blank=True, max_length=50, verbose_name="jira项目")),
                ("chat_id", models.CharField(blank=True, max_length=50, null=True, verbose_name="群聊id")),
                ("is_active", models.BooleanField(blank=True, max_length=50, null=True, verbose_name="激活")),
            ],
            options={
                "db_table": "ace_jira_project_chat",
            },
            bases=(models.Model, hutils.django.databases.ModelMixin),
        ),
    ]
