# Generated by Django 3.1.2 on 2021-06-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("endpoints", "0025_jiraprojectchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="departmentaccount",
            name="is_active",
            field=models.BooleanField(blank=True, max_length=50, null=True, verbose_name="是否在职"),
        ),
    ]
